"""Checked-in declarative Director workflow presets.

The HTTP surface accepts only a preset name, never a filesystem path.  Actual
ComfyUI graphs are generated by the same trusted compiler named in this
manifest and are exported separately by durable job id.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any

from .errors import ApiError


DIRECTOR_PRESET_MODES = ("r2v", "v2v", "rv2v")
_MANIFEST = Path(__file__).with_name("workflow_presets") / "director.json"


@lru_cache(maxsize=1)
def _load() -> dict[str, Any]:
    try:
        value = json.loads(_MANIFEST.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as error:
        raise ApiError(500, "workflow_manifest", "Director workflow manifest is unavailable") from error
    if not isinstance(value, dict) or value.get("schema_version") != 1:
        raise ApiError(500, "workflow_manifest", "Director workflow manifest schema is invalid")
    if value.get("compiler") != "h3_ref" or value.get("conditioner_node") != "MiniMaxH3ReferenceToVideo":
        raise ApiError(500, "workflow_manifest", "Director workflow manifest selected an untrusted compiler")
    presets = value.get("presets")
    if not isinstance(presets, dict) or set(presets) != set(DIRECTOR_PRESET_MODES):
        raise ApiError(500, "workflow_manifest", "Director workflow preset index is invalid")
    if any(not isinstance(presets[mode], dict) for mode in DIRECTOR_PRESET_MODES):
        raise ApiError(500, "workflow_manifest", "Director workflow preset is invalid")
    return value


def director_workflow_index() -> dict[str, Any]:
    value = _load()
    return {
        "schema_version": value["schema_version"],
        "id": value["id"],
        "display_name": value["display_name"],
        "compiler": value["compiler"],
        "conditioner_node": value["conditioner_node"],
        "modes": [
            {
                "mode": mode,
                "display_name": value["presets"][mode]["display_name"],
                "url": f"/api/workflows/director/{mode}",
                "download_url": f"/api/workflows/director/{mode}?download=1",
            }
            for mode in DIRECTOR_PRESET_MODES
        ],
    }


def director_workflow_preset(mode: str) -> dict[str, Any]:
    if mode not in DIRECTOR_PRESET_MODES:
        raise ApiError(404, "unknown_workflow_preset", "Director workflow preset does not exist")
    value = _load()
    # Round-trip makes callers unable to mutate the cached checked-in value.
    preset = json.loads(json.dumps(value["presets"][mode]))
    return {
        "schema_version": value["schema_version"],
        "manifest_id": value["id"],
        "kind": "template",
        "mode": mode,
        "compiler": value["compiler"],
        "conditioner_node": value["conditioner_node"],
        "trusted_compiler": value["trusted_compiler"],
        "model_binding_roles": list(value["model_binding_roles"]),
        "audio_output": json.loads(json.dumps(value["audio_output"])),
        "actual_workflow_export": value["actual_workflow_export"],
        **preset,
    }
